version: '3'

services:
  concourse-db:
    image: postgres:9.5
    volumes: ["./../postgres-data:/var/lib/postgresql/data"]
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: changeme
      PGDATA: /database

  concourse-web:
    image: concourse/concourse:3.0.1
    links: [concourse-db]
    command: web
    depends_on: [concourse-db]
    ports: 
      - "8080:8080"
      - "2222:2222"
    volumes: ["./../keys/web:/concourse-keys"]
    restart: unless-stopped # required so that it retries until conocurse-db comes up
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: concourse
      CONCOURSE_BASIC_AUTH_PASSWORD: changeme
      CONCOURSE_EXTERNAL_URL: "${CONCOURSE_EXTERNAL_URL}"
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse
      CONCOURSE_POSTGRES_PASSWORD: changeme
      CONCOURSE_POSTGRES_DATABASE: concourse

  concourse-worker:
    image: concourse/concourse:3.0.1
    privileged: true
    links: [concourse-web]
    depends_on: [concourse-web]
    command: worker
    volumes: ["./../keys/worker:/concourse-keys"]
    environment:
      CONCOURSE_TSA_HOST: concourse-web
      CONCOURSE_GARDEN_DNS_SERVER: 8.8.8.8
